/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hejin_ndk_Hello */

#ifndef _Included_com_hejin_ndk_Hello
#define _Included_com_hejin_ndk_Hello

#ifdef __cplusplus
}
#endif
#endif
JNIEXPORT jstring JNICALL
Java_com_hejin_ndk_Hello_haha(JNIEnv *env, jclass type, jstring hah_, jstring string_){
    return (*env)->NewStringUTF(env, "你好C");
}